version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      #- curl -sL https://deb.nodesource.com/setup_12.x | bash -
      #- apt-get install -y nodejs  #aws code build use ubuntu environement
       #-curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
       #-sudo yum install nodejs
       #-node -v
    - npm install -y npm@latest
    - npm install -g @angular/cli
    - rm package-lock.json


  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
    - echo build started on `date`
    - ng build
    - ls -l -F
     # - ng build --prod
  post_build:
    commands:
      - mv appspec.yml ./dist/my-dream-app
      - mv scripts ./dist/my-dream-app
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/my-dream-app
